"""add descricao_atividade to s2220_exame

Revision ID: 691b20ad5510
Revises: 0f9d9283425a
Create Date: 2026-04-16 23:28:32.507410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691b20ad5510'
down_revision = '0f9d9283425a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('s2220_exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao_atividade', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('s2220_exame', schema=None) as batch_op:
        batch_op.drop_column('descricao_atividade')

    # ### end Alembic commands ###
